# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Builds

on:
  push:
    branches: [master]
  pull_request:
    branches: [opened, labeled, master]
  issues:
   types: [opened, labeled]
  #pull_request:
  # types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
  MY_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}
      - run: npm cache verify
#      - run: npm cache clean -f
      - run: rm -rf package-lock.json 
#      - run: npm i -g npm@6
      - run: npm i --force
      - run: npm run production
      # - run: npm test
      - name: Save state
        run: echo "::save-state name={name}::{value}"

      - name: Set output
        run: echo "::set-output name={name}::{value}"
      - name: Deploy to gihub pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
